### ISSUE TITLE
Package documentation should have a section on logging filenames, line numbers, and stack traces

### ISSUE THREAD

**Issue by mgutz** [inconshreveable/log15#45]
i dont see any mention of it in doc.go

**Comment by mgutz** [comment]
I had to read the source code

`log15.SetHandler(log15.CallerFileHandler(log15.StdoutHandler)))`

**Comment by inconshreveable** [comment]
The API is documented (https://godoc.org/gopkg.in/inconshreveable/log15.v2#CallerFileHandler), but we should have a section in the package documentation that points you to it. I'll reopen this ticket and modify it to talk about including that in the documentation.

**Comment by ChrisHines** [comment]
Which part of the package documentation should we put this in? We could mention them (and a few other common ones) in the Handlers section, or we could have a whole new section about filenames, line numbers and stack traces. I am leaning toward the first option but am curious what others think before I start working on it.

**Comment by inconshreveable** [comment]
I'd vote for a separate section since it's a common topic of interest and having the bold heading would be helpful for people scanning through the docs to find it. This opinion is weakly held.

Something like "Logging File Names and Line Numbers" with a few examples illustrating the different format specifiers and their outputs.

**Comment by ChrisHines** [comment]
OK. I'll try to add a new section to the docs sometime this week for review.

**Comment by ChrisHines** [comment]
Section added.

@inconshreveable @mgutz please review.
