### ISSUE TITLE
Add automated CI /w coverage reports

### ISSUE THREAD

**Issue by inconshreveable** [inconshreveable/log15#48]

**Comment by GeertJohan** [comment]
:+1:

**Comment by GeertJohan** [comment]
When we're doing this, we should also think about what versions of go are supported. In an other project where I recently became maintainer we decided to support the last minor versions for the most recent two major versions of go (at this time go1.3.3 and go1.4.2). When a new major version of go is released (go 1.5) then the older version (go1.3.3) will be dropped after a month or so (best effort basis).

**Comment by inconshreveable** [comment]
I've set this up but I'm seeing failures on older versions of Go because of how go-stack's behavior changes depending on the version of Go. @ChrisHines thoughts? https://travis-ci.org/inconshreveable/log15

**Comment by ChrisHines** [comment]
I've run into this before. It happens because TravisCI installs the old versions of go in a directory that does not match the GOROOT the stdlib was build in, which breaks the logic in `stack.TrimRuntime`. I have one idea for a work around that I will try when I get a chance, but otherwise I consider it a bad behavior on TravisCI's part.

**Comment by inconshreveable** [comment]
interesting. I'd also be okay adding an exception for the test in travis too if you think that makes more sense

**Comment by ChrisHines** [comment]
Let me try my idea first, if it works it will be a better approach than how the package works now. If not, then we can look at ignoring that test in travis.

**Comment by inconshreveable** [comment]
👍

**Comment by ChrisHines** [comment]
My idea worked. github.com/go-stack/stack now builds and tests cleanly on all versions of Go: https://travis-ci.org/go-stack/stack/branches.

I reran the log15 build and it passes on all versions of Go, except 1.0. The culprit is the use of method values in the Syslog handlers. Method values [were added in Go 1.1](https://golang.org/doc/go1.1#method_values).

**Comment by inconshreveable** [comment]
hooray! thanks Chris! I'm okay not supporting 1.0. I'll adjust the .travis.yml and close this out
