### ISSUE TITLE
Faster discard and/or leveled filtering

### ISSUE THREAD

**Issue by jackc** [inconshreveable/log15#64]
I recommend log15 for [pgx](https://github.com/jackc/pgx), a database driver for PostgreSQL. I'm doing only a small amount of logging now. There is a small but measurable performance impact when enabling logging. A 63000ns query becomes 66000ns even when the log is filtered. Some of that is preparing the parameters to be logged, but at least 1000ns is just overhead for the log call. pgx is very focused on performance, so losing 5% even when logging is disabled is unfortunate. I work around it by checking if no logger is provided and skipping the logging call altogether.

Overall though, the performance is acceptable for my current uses. But I'd like to add some low-level, high-volume debug logging. The problem is when the logger is set to filter debug messages even the no-op calls would seriously degrade performance. So I can't add the debug logging because it would negatively impact people who only have logging set to error.

I know it kind of goes against the leveled logger interface, but is there any way to quickly determine if a given level will be discarded? I really need to skip the log call entirely to have acceptable performance. Otherwise, I probably will need to have an extra debug flag in pgx that turns on and off the extra logging.

If that's the solution, that's fine, just thought I'd see if there is a better built-in way.

**Comment by ChrisHines** [comment]
@jackc Thanks for the thoughtful question.

In general there is not a good way to determine if a given log event will get filtered because the `Handler` chain could include something like [EscalateErrHandler](https://godoc.org/gopkg.in/inconshreveable/log15.v2/ext#EscalateErrHandler) that will change the answer after the event is generated.

When you really need to skip the log call entirely then an `if` statement checking against an efficient to read configuration value is your best bet. This will avoid the overhead of converting the log call arguments to a `[]interface{}` and the internal log15 cost of capturing the call site information and allocating a `log15.Record`.

On the other hand, you might consider not coupling github.com/jackc/pgx to a specific logging package. See my [recent post](https://groups.google.com/d/msg/golang-nuts/K-q1fl8O0DY/SARRBEpI5d8J) on golang-nuts towards the bottom of [this discussion](https://groups.google.com/d/topic/golang-nuts/K-q1fl8O0DY/discussion) (and follow the links I provide) for why you should think about this carefully.

**Comment by jackc** [comment]
I agree about not coupling directly to a specific log package. pgx defines a pgx.Logger interface that is a subset of the log15 interface.

```go
// Logger is the interface used to get logging from pgx internals.
// https://github.com/inconshreveable/log15 is the recommended logging package.
// This logging interface was extracted from there. However, it should be simple
// to adapt any logger to this interface.
type Logger interface {
	// Log a message at the given level with context key/value pairs
	Debug(msg string, ctx ...interface{})
	Info(msg string, ctx ...interface{})
	Warn(msg string, ctx ...interface{})
	Error(msg string, ctx ...interface{})
}
```

I think adding a log level to pgx configuration is probably the right approach. That would give me back the 5% performance for people who only want error level messages and would allow a clean way for other logging packages to be supported in the same way.

**Comment by ChrisHines** [comment]
Sounds good.
