### ISSUE TITLE
New version or update v2 with #37?

### ISSUE THREAD

**Issue by raphael** [inconshreveable/log15#80]
My applications require the fix in #37 however the current v2 branch does not contain it which means I can't use the `gopkg.in` based import path. It would be asesome if that fix made it to the v2 branch but I understand the concern with breaking existing code in which case a v3 branch would be great too.

**Comment by inconshreveable** [comment]
log15 no longer supports gopkg.in or the v2 branch. the Go community has decided that the preferred dependency management strategy is the `vendor` folder as supported by Go 1.6+. Please use the `github.com/inconshreveable/log15` import and vendor the package appropriately with one of the many dependency vendoring tools

**Comment by raphael** [comment]
Aren't these two things orthogonal? as a consumer of the package I like having a stable branch that the author keeps backwards compatible. I will vendor it sure but if all my apps vendor the same version then I can rely on the interface being consistent in all of them. This is especially important when using packages that in turn use log15 - all packages must use a compatible interface i.e. the same version. As it stands what would you recommend doing, pinning to a random sha and making sure to vendor that sha across all the packages / apps? I may not even have that control...

**Comment by inconshreveable** [comment]
@raphael I agree with you, those things are orthogonal. The Go community seems to have mostly settled on two approaches:

- leaving the application developer with the problem of figuring out when the API changed and why
- never updating the API of a package

Right now, log15 is taking the position of documenting in the README.md the commit hash of all breaking API changes that are merged to the master branch so that you'll at least be able to reason about changes.
