### ISSUE TITLE
slog-rs: Rust port of log15

### ISSUE THREAD

**Issue by dpc** [inconshreveable/log15#92]
Hi, since "Imitation is the sincerest form of flattery" I just wanted to ping the author, that I liked log15 so much, that I had to port it to Rust:

https://github.com/dpc/slog-rs

The internals and some details are a very different due to rather different approach of both languages, but API should be immediately recognizable. 

Feel free to close this issue and happy gophering!

**Comment by inconshreveable** [comment]
wow, this is so cool. i'm really flattered! thanks for sharing with us =) i'll be following along slog's development

**Comment by dpc** [comment]
I'm getting close to releasing 1.0 of `slog-rs`. As ` log15` user in my Go projects I have couple of things to share that you might consider when working on log15.

Taking system time is costly:

https://github.com/inconshreveable/log15/blob/5146e0357e2b330b57698c6fc1fecfbfe2a898dc/logger.go#L104

If go runtime is not making any caching/etc. calling time.Now() will involved making a syscall, even for trace/debug records that will be discarded most of the time anyway.

In `slog-rs` I used to just lazily evaluate the value of time the first time anything actually requested it, but recently I've decided to just kick it out. If anyone wants any form of a timestamp, a lazily-evaluated value can be used instead.

I'd be guessing that taking a stacktrace:

https://github.com/inconshreveable/log15/blob/5146e0357e2b330b57698c6fc1fecfbfe2a898dc/logger.go#L108

is expensive too.  There are multiple other performance-focused little details that make `slog-rs` really fast. Generally no allocations are required except for initial phase, etc. It's hard for me to match them to Go, since I'm not that experienced Go user, and Go is not that performance focused language. But as a log15 user I wish it was as fast as possible given the platform (Go), so I can staff my code with Debug messages and not worry about them slowing everything down).

In `slog-rs` there are no special key names like `RecordKeyNames`:

https://github.com/inconshreveable/log15/blob/5146e0357e2b330b57698c6fc1fecfbfe2a898dc/logger.go#L109

instead lazy values can be functions (closures) taking `Record`, so user or a `Drain` (slog's name for `Handler`) can just pick their own names for key and values, and eg. format time the way they want etc.. Eg. https://github.com/dpc/slog-rs/blob/master/examples/file-line-module.rs#L12 - composing `file:line module` string of a given record under key `info`.

Maybe instead of taking stacktrace, a file, line, function etc. would do? At least in Rust taking them is almost free.

I have implemented a really cool compact format:

https://camo.githubusercontent.com/314d5a63dcedae371e3d61d67c4bd2883253d21c/687474703a2f2f692e696d6775722e636f6d2f503975327357502e706e67

and I wish log15 could have it. It makes reading logs on terminal much nicer, especially when a lot of values are involved.

**Comment by ChrisHines** [comment]
Taking the system time in Go is actually not that costly. Since Go v1.3 is does not make a system call on most modern machines or OSes. I found [this Cloudflare blog post](https://blog.cloudflare.com/its-go-time-on-linux/) that explains many of the details of how this works and has benchmark results that give an idea of how fast `time.Now` can be.

Taking a stack trace costs a lot more than getting the time, although the unavoidable part that log15 does every time you log with it is typically on the order of microseconds. Unfortunately Go doesn't have a cheap way to get file:line info that is similar to e.g. compiler provided macros I remember from my C/C++ days.

In my experience the most costly aspect of any logging solution is usually formatting the log event into the output bytes. Writing those bytes to the terminal or a file will typically introduce even more overhead.

That said, if you are looking for a Go logging package optimized for perfomance, https://github.com/uber-go/zap is worth a look.

If you want flexibility with an eye on performance, I recommend [github.com/go-kit/kit/log](https://github.com/go-kit/kit/tree/master/log) (disclaimer: I'm one of the authors). It's API was inspired heavily by log15 with an emphasis on simplicity and flexibility. It does not force you to pay the cost of taking stack traces or timestamps (although you can selectively opt-in to either). Implementing a custom format for Go kit logging is as simple as implementing a single method interface.

**Comment by dpc** [comment]
Thanks for all the information @ChrisHines . It's been very useful to me.

While it's nice that that `time.Now` is much faster then syscall  - it's still slow. And "order of microsecond" for stacktrace is prohibitively expensive.

IMO most important performance metric for logging is how fast are statements that are not even logged anywhere. Only then debug and trace level messages can be used liberally.  Ideally a log statement that is filtered out should take as close to 0 cycles as possible. Fast serialization etc. is obviously a nice thing too, but since there's already an overhead of eg. involving IO, overheads there are not that critical.

I really like `zap` speed. `kit/log` has a more familiar API and would be most easy for me to switch to from log15, while having an acceptable performance for me needs. Again, thanks for the pointers!

**Comment by helinwang** [comment]
```
 Call: stack.Caller(2), 
```

is indeed very expensive. log15 became a performance bottleneck due to this line, according to CPU profiler.
